version: "3.8"

services:
  miko:
    build:
      dockerfile: Dockerfile.dev
      context: ./miko
    depends_on:
      - redis
    volumes:
      - /miko/node_modules
      - ./miko:/miko
    env_file: ./miko/.env
    ports:
      - 5000:5000
    links: 
      - redis
    networks:
      - linkedlist-app

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/miko/redis/data
    networks:
      - linkedlist-app

networks:
  linkedlist-app:
    driver: bridge

volumes:
  redis-data:
    driver: local
