version: "3.3"

services:
  miko:
    build:
      dockerfile: Dockerfile
      context: ./miko
    container_name: miko
    depends_on:
      - redis
    volumes:
      - /miko/node_modules
      - ./miko:/miko
    env_file: ./miko/.env
    ports:
      - 5000:5000
    networks:
      - linkedlist-app

  redis:
    image: redis
    container_name: redis_db
    ports:
      - 6379:12279
    volumes:
      - ./redis-data:/app/redis/data
    networks:
      - linkedlist-app

networks:
  linkedlist-app:
    driver: bridge

volumes:
  redis-data:
