version: "3.8"

services:
  miko:
    build:
      dockerfile: Dockerfile.dev
      context: ./miko
    depends_on:
      - redis
    volumes:
      - /miko/node_modules
      - ./miko:/miko
    env_file: ./miko/.env
    ports:
      - 5000:5000
    links: 
      - redis
      - mailhog
    networks:
      - linkedlist-app

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/miko/redis/data
    networks:
      - linkedlist-app

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
      - 1025:1025
    environment: 
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes: 
      - maildir:/tmp

networks:
  linkedlist-app:
    driver: bridge

volumes:
  redis-data:
    driver: local
  maildir: {}
